const billings = [
  {
    id:1,
    createdAt: new Date('2019-12-17'),
    history:true,
    type:"Paiement",
    invoiceNumber:"",
    contractNumber:"000001",
    debit:800,
    credit:"",
    dueDate:"",
    document:true,
    lettering:"",
    recovery:"",
    actions:"",
  },
  {
    id:2,
    createdAt: new Date('2020-1-17'),
    history:true,
    type:"Paiement",
    invoiceNumber:"",
    contractNumber:"000001",
    debit:"",
    credit:300,
    dueDate:"",
    document:true,
    lettering:"",
    recovery:"",
    actions:"",
  },
  {
    id:3,
    createdAt: new Date('2020-2-3'),
    history:true,
    type:"Zob",
    invoiceNumber:"",
    contractNumber:"000001",
    debit:"",
    credit:150,
    dueDate:"",
    document:true,
    lettering:"",
    recovery:"",
    actions:"",
  },
  {
    id:4,
    createdAt: new Date('2020-1-21'),
    history:true,
    type:"Zob",
    invoiceNumber:"",
    contractNumber:"000001",
    debit:"",
    credit:150,
    dueDate:"",
    document:true,
    lettering:"",
    recovery:"",
    actions:"",
  },
];

export default billings