const billings = [
  {
    id:1,
    createdAt: "12/04/2020",
    history:true,
    type:"Paiement",
    invoiceNumber:"",
    contractNumber:"000001",
    debit:200,
    credit:"",
    dueDate:"",
    document:true,
    lettering:"",
    recovery:"",
    actions:"",
  },
  {
    id:2,
    createdAt: "12/04/2020",
    history:true,
    type:"Paiement",
    invoiceNumber:"",
    contractNumber:"000001",
    debit:"",
    credit:300,
    dueDate:"",
    document:true,
    lettering:"",
    recovery:"",
    actions:"",
  },
  {
    id:3,
    createdAt: "12/04/2020",
    history:true,
    type:"Zob",
    invoiceNumber:"",
    contractNumber:"000001",
    debit:"",
    credit:150,
    dueDate:"",
    document:true,
    lettering:"",
    recovery:"",
    actions:"",
  },
  {
    id:4,
    createdAt: "12/04/2020",
    history:true,
    type:"Zob",
    invoiceNumber:"",
    contractNumber:"000001",
    debit:"",
    credit:150,
    dueDate:"",
    document:true,
    lettering:"",
    recovery:"",
    actions:"",
  },
];

export default billings